language: php
sudo: false

php:
- 7.3

cache:
    pip: true
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

install:
    - composer update --prefer-dist --no-interaction --quiet
    - ./vendor/bin/simple-phpunit install

script:
    - ./vendor/bin/simple-phpunit
